apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otp-relay
  namespace: otp-relay
spec:
  ingressClassName: traefik
  rules:
    - host: otp-relay.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: otp-relay
                port:
                  number: 80
