apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otp-relay
  namespace: otp-relay
spec:
  ingressClassName: traefik
  rules:
    - host:  __TLS_HOST__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: otp-relay
                port:
                  number: 80
