apiVersion: v1
kind: Service
metadata:
  name: otp-monitor
  namespace: otp-relay
  labels:
    app: otp-monitor
    metrics: enabled
spec:
  type: ClusterIP
  selector:
    app: otp-monitor
  ports:
    - name: metrics
      port: 9101
      targetPort: 9101
      protocol: TCP
