apiVersion: v1
kind: Service
metadata:
  name: otp-redis
  namespace: otp-relay
  labels:
    app: otp-redis-haproxy
spec:
  type: ClusterIP
  selector:
    app: otp-redis-haproxy
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: otp-redis-headless
  namespace: otp-relay
  labels:
    app: otp-redis
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: otp-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
