apiVersion: v1
kind: PersistentVolume
metadata:
  name: otp-redis-devprod-0-nfs-pv
  labels:
    app: otp-redis
    redis-pod: otp-redis-0
    storage-role: redis-data
    deployment-namespace: otp-relay-devprod
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: otp-redis-devprod-nfs
  mountOptions:
    - nfsvers=4.1
  claimRef:
    namespace: otp-relay-devprod
    name: redis-data-otp-redis-0
  nfs:
    server: nfsdevprod.init-db.lan
    path: /srv/nfs/otp-relay-devprod/redis/otp-redis-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: otp-redis-devprod-1-nfs-pv
  labels:
    app: otp-redis
    redis-pod: otp-redis-1
    storage-role: redis-data
    deployment-namespace: otp-relay-devprod
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: otp-redis-devprod-nfs
  mountOptions:
    - nfsvers=4.1
  claimRef:
    namespace: otp-relay-devprod
    name: redis-data-otp-redis-1
  nfs:
    server: nfsdevprod.init-db.lan
    path: /srv/nfs/otp-relay-devprod/redis/otp-redis-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: otp-redis-devprod-2-nfs-pv
  labels:
    app: otp-redis
    redis-pod: otp-redis-2
    storage-role: redis-data
    deployment-namespace: otp-relay-devprod
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: otp-redis-devprod-nfs
  mountOptions:
    - nfsvers=4.1
  claimRef:
    namespace: otp-relay-devprod
    name: redis-data-otp-redis-2
  nfs:
    server: nfsdevprod.init-db.lan
    path: /srv/nfs/otp-relay-devprod/redis/otp-redis-2
