apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otp-relay
  namespace: observability
  labels:
    app: otp-relay
spec:
  namespaceSelector:
    matchNames:
      - otp-relay
  selector:
    matchLabels:
      app: otp-relay
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
