apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otp-monitor
  namespace: observability
  labels:
    app: otp-monitor
spec:
  namespaceSelector:
    matchNames:
      - otp-relay
  selector:
    matchLabels:
      app: otp-monitor
      metrics: enabled
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
